#!/bin/bash

set -euo pipefail

function usage() {
    echo -n "Usage: $(basename "$0")

Run an interactive R shell in a container.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ];
then
    if [ "${1:-}" = "--help" ];
    then
        usage
    else
        docker-compose run --rm r
    fi
fi
