#!/bin/bash

set -euo pipefail

function usage() {
    echo -n "Usage: $(basename "$0")

Run a development server accessible at http://localhost:8000 that will compile
and live-reload any RMarkdown files in this repo.

Navigate to http://localhost:8000 to view a directory tree and select the file
you're interested in.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ];
then
    if [ "${1:-}" = "--help" ];
    then
        usage
    else
        if [ -z "$1" ];
        then
            docker-compose run --rm --service-ports watch
        else
            docker-compose run --rm --service-ports watch R --vanilla -e "servr::rmdv2(dir='${1}', host='0.0.0.0', port=8000)"
        fi
    fi
fi
